version: '3'

services:

  react:
    container_name: react
    build:
      context: react/
      dockerfile: Dockerfile
    volumes:
      - './react:/app'
    ports:
      - 80:80
    depends_on:
      - nodejs
      
  nodejs:
    container_name: nodejs
    build:
      context: nodejs/
      dockerfile: Dockerfile
    volumes:
      - './nodejs:/app'
      - '/app/node_modules'
    ports:
      - 3008:3008
    expose:
      - 3008



